#!/bin/bash


target_uuid="6b70f079-89d7-4ff3-a95f-5904432053ad"

# Use blkid to get the UUID of the device you want to check (e.g., /dev/sdb1)
device_uuid=$(blkid -s UUID -o value /dev/sdb1)

# Check if the device's UUID matches the target UUID
if [ "$device_uuid" = "$target_uuid" ]; then

   # sdb2 is for VM window.
   sudo mount /dev/sdb1 /mnt/HDD/LINUX_EXT4_datausager_sdb1/
   sleep 0.1
   sudo mount /dev/sdb4 /mnt/HDD/Games_HDD_ntfs_sdb4/
   sleep 0.1
   sudo mount /dev/sdb3 /mnt/HDD/Media_file_hdd_sdb3/


fi
